### ISSUE TITLE
Why do you invert the matrix before making the transformation?

### ISSUE THREAD

**Issue by Giammarco07** [wuneng/WarpAffine2GridSample#2]
I went through the various steps and managed to get to the final transformation matrix, but according to my mathematical calculations I shouldn't do the inverse of "param" before. Obviously applying the transformation without the inverse I don't get the correct result as yours... Could you please explain to me why it should be done?

**Comment by wuneng** [comment]
Hi,
 Thanks for your interest. It has been a long time since I have used this code and I don't remember how to derive.If you want to figure out why it should work,  you may dig into [this tutorial](https://kornia.readthedocs.io/en/latest/tutorials/warp_affine.html) in Kornia.
 Sorry I can not offer more insights.

**Comment by Giammarco07** [comment]
I thank you the same but this tutorial is not related to my question... I will try to find what I am looking for in Kornia documentation.

**Comment by lililiiiiiiiiii** [comment]
> I thank you the same but this tutorial is not related to my question... I will try to find what I am looking for in Kornia documentation.
hi,did you solve this problem,i readed Kornia's tutorial,and according to my understanding, the matrix here is not inverted.
